[package]
name = "poly-commit"
version = "0.1.0"
authors = [ "arkworks contributors" ]
description = "A library for constructing polynomial commitment schemes for use in zkSNARKs"
repository = "https://github.com/scipr-lab/poly-commit"
documentation = "https://docs.rs/poly-commit/"
keywords = ["cryptography", "polynomial commitments", "elliptic curves", "pairing"]
categories = ["cryptography"]
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

[dependencies]
#ark-algebra = { git = "https://github.com/arkworks-rs/algebra" }
#algebra-benches = { git = "https://github.com/arkworks-rs/algebra" }

ark-std = { git = "https://github.com/arkworks-rs/utils" }
bench-utils = { git = "https://github.com/arkworks-rs/utils" }

ark-ff = { git = "https://github.com/arkworks-rs/algebra" }
ark-ec = { git = "https://github.com/arkworks-rs/algebra" }
ark-poly = { git = "https://github.com/arkworks-rs/algebra" }
ark-serialize = { git = "https://github.com/arkworks-rs/algebra" }

ark-snark = { git = "https://github.com/arkworks-rs/snark" }
ark-relations = { git = "https://github.com/arkworks-rs/snark" }
ark-r1cs-std = { git = "https://github.com/arkworks-rs/r1cs-std", branch = "update-to-ark" }
crypto-primitives = { git = "https://github.com/arkworks-rs/crypto-primitives" }

ark-bls12-377 = { git = "https://github.com/arkworks-rs/curves" }
ark-bls12-381 = { git = "https://github.com/arkworks-rs/curves" }
ark-ed-on-bls12-381 = { git = "https://github.com/arkworks-rs/curves" }
ark-mnt4-298 = { git = "https://github.com/arkworks-rs/curves" }
ark-mnt6-298 = { git = "https://github.com/arkworks-rs/curves" }
ark-mnt4-753 = { git = "https://github.com/arkworks-rs/curves" }
ark-mnt6-753 = { git = "https://github.com/arkworks-rs/curves" }

rand_core = { version = "0.5" }
num-traits = { version = "0.2", default-features = false }
digest = "0.8"
rayon = { version = "1", optional = true }
derivative = { version = "2", features = [ "use_core" ] }
nonnative = { git = "ssh://git@github.com/arkworks-rs/nonnative.git", version = "0.0.4" }

[dev-dependencies]
rand = { version = "0.7", default-features = false }
blake2 = { version = "0.8", default-features = false }

[profile.release]
opt-level = 3
lto = "thin"
incremental = true
debug = true

[profile.test]
opt-level = 3
debug-assertions = true
incremental = true
debug = true

[features]
default = ["std", "parallel"]
std = [ "ark-ff/std", ]
#print-trace = [ "bench-utils/print-trace" ]
parallel = [ "std", "ark-ff/parallel", "rayon" ]
